FROM node:14.8.0

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
RUN npm install git+https://github.com/thesimj/js-chacha20.git
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 443/tcp
CMD HTTPS=true SSL_CRT_FILE=$TLS_CRT SSL_KEY_FILE=$TLS_KEY npm start
